### ISSUE TITLE
Support for gmail?

### ISSUE THREAD

**Issue by fr3fou** [xhit/go-simple-mail#10]
Many clients simply error out on gmail due to "Less Secure Access"; Does this library have a fix for that?

**Comment by xhit** [comment]
You need turn on Less Secure Apps in Gmail account. See https://devanswers.co/allow-less-secure-apps-access-gmail-account/

**Comment by fr3fou** [comment]
The problem is that this option keeps getting turned off every month

**Comment by xhit** [comment]
If LSA is resetting is because you need to add a recovery email and phone in the Gmail account. After that, reset your password.

Also, this package use SMTP protocol to send emails. If you really need to use Gmail accounts without having problems I recommend use OAuth2 Gmail API, see https://medium.com/wesionary-team/sending-emails-with-go-golang-using-smtp-gmail-and-oauth2-185ee12ab306

A working project using OAuth2: https://github.com/BinodKafle/gomail

**Comment by fr3fou** [comment]
Enabled those, hopefully they fix my issue!
